spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    platform: postgres
    url: <tbd>
    username: <tbd>
    driverClassName: org.postgresql.Driver

openweather:
  url: http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={appId}
  appId: <tbd>

logging:
  level:
    root: info

